//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showrma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionOfSupply
    {
        public int Id { get; set; }
        public Nullable<int> ZakazShavaId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ZakazShava ZakazShava { get; set; }
    }
}
