//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showrma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazShava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZakazShava()
        {
            this.CompositionOfSupply = new HashSet<CompositionOfSupply>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> ColorId { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompositionOfSupply> CompositionOfSupply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual Type Type { get; set; }
    }
}
